name: WP-Discourse Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }}
    strategy:
      matrix:
        include:
          - php: "5.6"
            sniff: true
          - php: "7.0"
            sniff: true
          - php: "7.1"
            sniff: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - uses: php-actions/composer@v5
      - name: Install Tools
        if: "matrix.sniff"
        run: |
          git clone --depth 1 git://github.com/phpenv/phpenv.git ~/.phpenv
          export PATH="$HOME/.phpenv/bin:$PATH"
          phpenv rehash
          sudo npm install -g jshint
          wget https://develop.svn.wordpress.org/trunk/.jshintrc
      - name: Syntax Check
        run: |
          find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
      - name: JSHint
        if: "matrix.sniff"
        run: |
          jshint .
      - name: WordPress Coding Standards
        if: "matrix.sniff"
        run: |
          vendor/bin/phpcs -p -s -v -n .
